{
 "title": "Aleo Logs",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Consensus details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Consensus status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{unit=\"validator.service\"} |= `Advanced to block`"
    },
    {
     "expr": "{unit=\"validator.service\"} |= `Committing a subdag`"
    }
   ]
  },
  {
   "title": "block_synced",
   "type": "logs",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "{job=\"systemd-journal\", unit=\"validator.service\"} |= `Updating is_block_synced`"
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Warnings",
   "type": "logs",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{unit=\"validator.service\"} |~ `WARN`"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{unit=\"validator.service\"} |= `ERR`"
    }
   ]
  },
  {
   "title": "consensus_status",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{unit=\"validator.service\"}"
    }
   ]
  }
 ]
}