server:
  http_listen_port: 9080
  http_listen_address: 0.0.0.0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: journal
    journal:
      json: false
      max_age: 12h
      path: /var/log/journal
      #matches: _SYSTEM_UNIT=validator.service
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'

  - job_name: mock-logs
    static_configs:
      - targets: ['localhost']
        labels:
          job: mock-logs
          __path__: /etc/promtail/mock-data/mock-aleo.log
    pipeline_stages:
    - regex:
        expression: '\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d+Z\\s+(TRACE|DEBUG|INFO|WARN|ERROR|FATAL)'
    - labels:
        log_level:




